Implement controller for mkspipeline
MiniTeks/mks-server pull request #43
Opened 2022-02-21 12:45 UTC by UtkarshChaurasia

- Create mkspipeline resource
- Generate deepcopy
- Implement controller for mkspipeline
- Create CRD for mkspipeline
- Fixes #42

2022-02-22 08:34 UTC, avinal requested changes
Looks nice, please add the copyright notices too, where it is missing.

2022-02-23 09:55 UTC, RAMESSESII2 approved these changes
lgtm

2022-03-01 06:37 UTC, avinal commented on config/mksResourceExample/mkspipeline-eg.yaml
> +  name: test-pipeline3
```suggestion
  name: test-pipeline
```

2022-03-01 06:47 UTC, avinal approved these changes

2022-03-01 06:52 UTC, RAMESSESII2 approved these changes
lgtm

2022-03-01 06:52 UTC, merged